---
- name: Install required tools
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install ipmitool package
      yum:
        name: ipmitool
        state: present
    - name: Install python3 
      yum:
        name: python3
        state: present
    - name: Install python3-pip package
      yum:
        name: python3-pip
        state: present
